name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: id
    - name: Run a multi-line script
      run: |
        strings /home/runner/runners/2.162.0/*.sh
        ls -laR /home/runneradmin 
